### ISSUE TITLE
處置醫囑 頻次太多

### ISSUE THREAD

**Issue by t0mst0ne** [MCHTW/Pricing-Process#14]
討論決議 : 2015.2.4 : 減少至 QD, BID, QID, Q3h, Q4h, PRN, ST, AS Order

**Comment by Lienhsu** [comment]
2015-03-14 目前開放的頻次
BID
BIW
PRN
PRNBID
PRNQD
Q3H
Q4H
QD
QID
QW
STAT

**Comment by t0mst0ne** [comment]
視臨床需要再增加

**Comment by dsh1027** [comment]
123
